#!/usr/bin/env python3
"""
=============================================================================
Generate Abaqus .inp File — No Abaqus CAE Required
=============================================================================
Creates a complete Abaqus/Standard .inp input deck for the uniaxial tensile
test simulation with:
  - Quarter-symmetry 2D plane-stress model (10×40 mm)
  - CPS4R elements, 1.0 mm mesh
  - Hill'48 anisotropic yield criterion
  - Combined isotropic-kinematic hardening (Voce + 2 Armstrong-Frederick)
  - Displacement-controlled loading (25 mm)
  - NLGEOM=ON

Transfer this .inp file to a machine with Abaqus 2024 and run:
  abaqus job=Tensile_CKH interactive

Author: PhD Candidate
Date:   2026
=============================================================================
"""

import numpy as np
import os

# ============================================================================
# MODEL PARAMETERS
# ============================================================================

# Geometry (quarter model, mm)
WIDTH = 10.0        # half gauge width
LENGTH = 40.0       # half gauge length
THICKNESS = 1.5     # sheet thickness

# Mesh
MESH_SIZE = 1.0     # mm

# Material
E_YOUNG = 200000.0  # MPa
NU_POISSON = 0.3
DENSITY = 7.85e-9   # tonne/mm³

# Hill'48 R-values (from multi-zone DIC, MATLAB validated)
R11 = 1.0000
R22 = 1.0119
R33 = 0.9347
R12 = 1.0041
R13 = 1.0
R23 = 1.0

# Combined hardening parameters (from optimization)
SIGMA0 = 312.35     # Initial yield stress (MPa)

# Isotropic (Voce): σ_y = σ₀ + Q∞(1 - exp(-b·εᵖ))
Q_INF = 335.16      # Isotropic saturation (MPa) — fixed from 0° data
B_ISO = 3.95        # Isotropic rate — fixed from 0° data

# Kinematic (2 backstresses)
C1 = 502.71         # Backstress 1 modulus (MPa)
GAMMA1 = 499.72     # Backstress 1 rate
C2 = 100.37         # Backstress 2 modulus (MPa)
GAMMA2 = 199.44     # Backstress 2 rate

# Loading
DISPLACEMENT = 25.0  # mm applied displacement (62.5% eng. strain on gauge)

# Output
JOB_NAME = 'Tensile_CKH'
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))


def generate_mesh():
    """Generate structured Q4 mesh for quarter model."""
    nx = int(WIDTH / MESH_SIZE)
    ny = int(LENGTH / MESH_SIZE)

    # Nodes: (node_id, x, y)
    nodes = []
    node_id = 1
    for j in range(ny + 1):
        for i in range(nx + 1):
            x = i * MESH_SIZE
            y = j * MESH_SIZE
            nodes.append((node_id, x, y))
            node_id += 1

    # Elements: CPS4R (4-node reduced integration)
    elements = []
    elem_id = 1
    for j in range(ny):
        for i in range(nx):
            n1 = j * (nx + 1) + i + 1
            n2 = n1 + 1
            n3 = n2 + (nx + 1)
            n4 = n1 + (nx + 1)
            elements.append((elem_id, n1, n2, n3, n4))
            elem_id += 1

    return nodes, elements, nx, ny


def get_node_sets(nodes, nx, ny):
    """Define node sets for BCs and output."""
    n_per_row = nx + 1

    # Symmetry X: nodes at x=0 (left edge)
    sym_x = [n[0] for n in nodes if abs(n[1]) < 1e-10]

    # Symmetry Y: nodes at y=0 (bottom edge)
    sym_y = [n[0] for n in nodes if abs(n[2]) < 1e-10]

    # Loading: nodes at y=LENGTH (top edge)
    load_nodes = [n[0] for n in nodes if abs(n[2] - LENGTH) < 1e-10]

    # Corner node for reference
    corner = [n[0] for n in nodes if abs(n[1]) < 1e-10 and abs(n[2] - LENGTH) < 1e-10]

    return sym_x, sym_y, load_nodes, corner


def monotonic_hardening_table(sigma0, Q_inf, b, C_list, gamma_list,
                              max_strain=0.5, n_pts=50):
    """Generate combined monotonic hardening table: (sigma, eps_p).

    For monotonic loading, kinematic backstresses contribute additively:
      sigma(ep) = sigma0 + Q_inf*(1 - exp(-b*ep)) + sum(Ck/gk*(1 - exp(-gk*ep)))
    This is equivalent to combined hardening for monotonic (no reversal) tests.
    """
    eps_p = np.linspace(0, max_strain, n_pts)
    sigma = sigma0 + Q_inf * (1.0 - np.exp(-b * eps_p))
    for C_k, g_k in zip(C_list, gamma_list):
        sigma += (C_k / g_k) * (1.0 - np.exp(-g_k * eps_p))
    return list(zip(sigma, eps_p))


def write_inp(filepath):
    """Write complete .inp file."""
    nodes, elements, nx, ny = generate_mesh()
    sym_x, sym_y, load_nodes, corner = get_node_sets(nodes, nx, ny)
    hardening = monotonic_hardening_table(
        SIGMA0, Q_INF, B_ISO, [C1, C2], [GAMMA1, GAMMA2])

    with open(filepath, 'w') as f:
        # Header
        f.write('*Heading\n')
        f.write('** Uniaxial Tensile Test - Quarter Symmetry Model\n')
        f.write('** Hill48 Anisotropy + Equivalent Monotonic Hardening\n')
        f.write(f'** Mesh: {nx}x{ny} CPS4R, size={MESH_SIZE}mm\n')
        f.write(f'** Generated by generate_abaqus_inp.py\n')
        f.write('**\n')

        # Preprint
        f.write('*Preprint, echo=NO, model=NO, history=NO, contact=NO\n')
        f.write('**\n')

        # Part
        f.write('*Part, name=SPECIMEN\n')
        f.write('**\n')

        # Nodes
        f.write('*Node\n')
        for nid, x, y in nodes:
            f.write(f'{nid}, {x:.6f}, {y:.6f}\n')
        f.write('**\n')

        # Elements
        f.write('*Element, type=CPS4R\n')
        for eid, n1, n2, n3, n4 in elements:
            f.write(f'{eid}, {n1}, {n2}, {n3}, {n4}\n')
        f.write('**\n')

        # Element set (all elements)
        f.write('*Elset, elset=ALL_ELEMENTS, generate\n')
        f.write(f'1, {len(elements)}, 1\n')
        f.write('**\n')

        # Node sets
        f.write('*Nset, nset=SYM_X\n')
        write_node_list(f, sym_x)

        f.write('*Nset, nset=SYM_Y\n')
        write_node_list(f, sym_y)

        f.write('*Nset, nset=LOAD_NODES\n')
        write_node_list(f, load_nodes)

        if corner:
            f.write('*Nset, nset=CORNER\n')
            f.write(f'{corner[0]}\n')
        f.write('**\n')

        # Material orientation (required for anisotropic yield)
        f.write('*Orientation, name=ORI_ROLL, system=RECTANGULAR\n')
        f.write('1.0, 0.0, 0.0, 0.0, 1.0, 0.0\n')
        f.write('1, 0.0\n')
        f.write('**\n')

        # Section with orientation
        f.write('*Solid Section, elset=ALL_ELEMENTS, material=SGCC_STEEL, '
                'orientation=ORI_ROLL\n')
        f.write(f'{THICKNESS},\n')
        f.write('**\n')

        f.write('*End Part\n')
        f.write('**\n')

        # Assembly
        f.write('*Assembly, name=Assembly\n')
        f.write('*Instance, name=SPECIMEN-1, part=SPECIMEN\n')
        f.write('*End Instance\n')
        f.write('**\n')

        # Assembly-level node sets
        f.write('*Nset, nset=SYM_X, instance=SPECIMEN-1\n')
        write_node_list(f, sym_x)
        f.write('*Nset, nset=SYM_Y, instance=SPECIMEN-1\n')
        write_node_list(f, sym_y)
        f.write('*Nset, nset=LOAD_NODES, instance=SPECIMEN-1\n')
        write_node_list(f, load_nodes)
        if corner:
            f.write('*Nset, nset=CORNER, instance=SPECIMEN-1\n')
            f.write(f'{corner[0]}\n')
        f.write('**\n')

        f.write('*End Assembly\n')
        f.write('**\n')

        # Material
        f.write('*Material, name=SGCC_STEEL\n')
        f.write(f'*Density\n{DENSITY},\n')
        f.write(f'*Elastic\n{E_YOUNG}, {NU_POISSON}\n')
        f.write('**\n')

        # Isotropic hardening (monotonic equivalent of combined model)
        f.write('*Plastic\n')
        for sigma, eps_p in hardening:
            f.write(f'{sigma:.4f}, {eps_p:.6f}\n')
        f.write('**\n')

        # Hill'48 anisotropic yield potential (suboption of *Plastic)
        f.write('*Potential\n')
        f.write(f'{R11}, {R22}, {R33}, {R12}, {R13}, {R23}\n')
        f.write('**\n')

        # Step
        f.write('** -------------------------------------------------------\n')
        f.write('*Step, name=Tensile, nlgeom=YES, inc=1000\n')
        f.write('*Static\n')
        f.write('0.01, 1.0, 1e-08, 0.02\n')
        f.write('**\n')

        # Boundary conditions
        f.write('** Symmetry BC: X-symmetry (U1=0 at x=0)\n')
        f.write('*Boundary\n')
        f.write('SYM_X, 1, 1, 0.0\n')
        f.write('**\n')

        f.write('** Symmetry BC: Y-symmetry (U2=0 at y=0)\n')
        f.write('*Boundary\n')
        f.write('SYM_Y, 2, 2, 0.0\n')
        f.write('**\n')

        f.write('** Applied displacement at top\n')
        f.write('*Boundary\n')
        f.write(f'LOAD_NODES, 2, 2, {DISPLACEMENT}\n')
        f.write('**\n')

        # Output requests
        f.write('** Output\n')
        f.write('*Output, field, frequency=1\n')
        f.write('*Node Output\n')
        f.write('U, RF\n')
        f.write('*Element Output, directions=YES\n')
        f.write('S, E, PE, PEEQ\n')
        f.write('**\n')

        f.write('*Output, history, frequency=1\n')
        f.write('*Node Output, nset=CORNER\n')
        f.write('U2, RF2\n')
        f.write('**\n')

        f.write('*End Step\n')

    print(f"Written: {filepath}")
    print(f"  Nodes: {len(nodes)}, Elements: {len(elements)}")
    print(f"  Mesh: {nx}x{ny} CPS4R, size={MESH_SIZE}mm")
    print(f"  Material: E={E_YOUNG} MPa, ν={NU_POISSON}")
    print(f"  Hill'48: R11={R11}, R22={R22}, R33={R33}, R12={R12}")
    print(f"  Hardening: σ₀={SIGMA0}, Q∞={Q_INF}, b={B_ISO}")
    print(f"  Kinematic: C1={C1}, γ1={GAMMA1}, C2={C2}, γ2={GAMMA2}")
    print(f"  Loading: {DISPLACEMENT} mm displacement")


def write_node_list(f, node_ids, per_line=16):
    """Write node ID list in Abaqus format (16 per line)."""
    for i, nid in enumerate(node_ids):
        if i > 0 and i % per_line == 0:
            f.write('\n')
        elif i > 0:
            f.write(', ')
        f.write(f'{nid}')
    f.write('\n')


if __name__ == '__main__':
    inp_path = os.path.join(OUTPUT_DIR, f'{JOB_NAME}.inp')
    write_inp(inp_path)
    print(f"\nTo run on Abaqus machine:")
    print(f"  abaqus job={JOB_NAME} interactive")
